/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 16 01:09:46 GMT 2017
 */

package org.asynchttpclient.handler.resumable;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import org.asynchttpclient.AbstractBasicTest;
import org.asynchttpclient.AsyncHandler;
import org.asynchttpclient.filter.FilterContext;
import org.asynchttpclient.handler.resumable.ResumableIOExceptionFilter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ResumableIOExceptionFilter_ESTest extends ResumableIOExceptionFilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResumableIOExceptionFilter resumableIOExceptionFilter0 = new ResumableIOExceptionFilter();
      // Undeclared exception!
      try { 
        resumableIOExceptionFilter0.filter((FilterContext<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.asynchttpclient.handler.resumable.ResumableIOExceptionFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ResumableIOExceptionFilter resumableIOExceptionFilter0 = new ResumableIOExceptionFilter();
      IOException iOException0 = mock(IOException.class, new ViolatedAssumptionAnswer());
      AbstractBasicTest.AsyncHandlerAdapter abstractBasicTest_AsyncHandlerAdapter0 = new AbstractBasicTest.AsyncHandlerAdapter();
      FilterContext<String> filterContext0 = (FilterContext<String>) mock(FilterContext.class, new ViolatedAssumptionAnswer());
      doReturn("i?`7,").when(filterContext0).toString();
      doReturn((AsyncHandler) null).when(filterContext0).getAsyncHandler();
      doReturn(iOException0).when(filterContext0).getIOException();
      FilterContext<String> filterContext1 = resumableIOExceptionFilter0.filter(filterContext0);
      assertSame(filterContext1, filterContext0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ResumableIOExceptionFilter resumableIOExceptionFilter0 = new ResumableIOExceptionFilter();
      FilterContext<Object> filterContext0 = (FilterContext<Object>) mock(FilterContext.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(filterContext0).toString();
      doReturn((IOException) null).when(filterContext0).getIOException();
      FilterContext<Object> filterContext1 = resumableIOExceptionFilter0.filter(filterContext0);
      assertSame(filterContext1, filterContext0);
  }
}
